project/Employees/Employees/Models/Autorisation/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Employees.Models.Autorisation
{
    public class Login
    {
        [Display(Name = "Логин")]
        [Required(ErrorMessage = "Пожалуйста, введите свой логин")]
        public string Name { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Пароль")]
        [Required(ErrorMessage = "Пожалуйста, введите свой пароль")]
        public string Password { get; set; }
    }
}

project/Employees/Employees/Controllers/AuthorizationController.cs
using Employees.BL.Manager;
using Employees.Models;
using Employees.Models.Autorisation;
using System;
using System.Web.Mvc;
using System.Web.Security;

namespace Employees.Controllers
{
    public class AuthorizationController : Controller
    {
        // GET: Authorization
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult ValidateUserAction(string Login, string Password)
        {
            //if (string.IsNullOrEmpty(Login))
            //{
            //    ViewBag.Success = false;
            //    ViewBag.Message = "Введите логин и пароль";
            //    return View("Index");
            //}
            //Result result = UserManager.CheckValidationUser(Login, Password);
            //if (result.Success && result.ResultObject != null)
            //{
            //    ViewBag.Success = true;
            //    FormsAuthentication.SetAuthCookie((result.ResultObject as User).Login, true);
            //}
            //else
            //    ViewBag.Success = false;
            //ViewBag.Message = result.Message;
            return View("Index");
        }

        [HttpGet]
        public ActionResult RegistrationUser()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RegistrationUser(RegisterUser user)
        {
            if (!ModelState.IsValid)
                return View(user);

            if (user == null)
            {
                throw new Exception();
            }
            var result = UserManager.GetManager.Save(user);
            if (!result.Success)
                return HttpNotFound();
            return View();

        }


        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Login model)
        {
            if (ModelState.IsValid)
            {
                // поиск пользователя в бд
                User user = null;

                var result = UserManager.GetManager.GetUserByNameAndPassword(model.Name, model.Password);
                if (!result.Success)
                {
                    ModelState.AddModelError("", result.Message);
                    return View(model);
                }
                user = result.ResultEntity;
                if (user != null)
                {
                    FormsAuthentication.SetAuthCookie(user.Login, true);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Пользователя с таким логином и паролем нет");
                }
            }

            return View(model);
        }

        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegisterUser model)
        {
            //if (ModelState.IsValid)
            //{
            //    User user = null;
            //    Result result = UserManager.CheckValidationUser(model.Name, model.Password);
            //    if (!result.Success)
            //    {
            //        ModelState.AddModelError("", result.Message);
            //        return View(model);
            //    }
            //    user = result.ResultObject as User;
            //    if (user == null)
            //    {
            //        // создаем нового пользователя

            //        UserManager.GetManager().Update(model);


            //        Result result1 = UserManager.CheckValidationUser(model.Name, model.Password);
            //        if (!result.Success)
            //        {
            //            ModelState.AddModelError("", result1.Message);
            //            return View(model);
            //        }
            //        user = result1.ResultObject as User;
            //        // если пользователь удачно добавлен в бд
            //        if (user != null)
            //        {
            //            FormsAuthentication.SetAuthCookie(user.Login, true);
            //            return RedirectToAction("Index", "Home");
            //        }
            //    }
            //    else
            //    {
            //        ModelState.AddModelError("", "Пользователь с таким логином уже существует");
            //    }
            //}

            return View(model);
        }
        public ActionResult Logoff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }




    }
}

project/Employees/Employees/Views/Authorization/Index.cshtml
@model Employees.Models.Autorisation.Login
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_layout.cshtml";
}

<h2>Авторизация</h2>
@using (Html.BeginForm("Login", "Authorization", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    if (!string.IsNullOrEmpty(ViewBag.Message))
    {
        <h2>@ViewBag.Message</h2>
    }
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row form-group">
        <label class="control-label">
            Login <input class="form-control" type="text" name="Name">
        </label>
    </div>
    <div class="row  form-group">
        <label class="control-label">
            Password<input class="form-control" type="password" name="Password">
        </label>
</div>
    <div class="row  form-group">
        <input class = "btn btn-success" type="submit" value="Отправить" onclick="LoginAction_Click" />
    </div>
}
<div class="row">
   @Html.ActionLink("Регистрация", "RegistrationUser", "Authorization")
</div>

project/Employees/Employees/Views/Authorization/Login.cshtml
@model Employees.Models.Autorisation.Login

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/_layout.cshtml";
}

<h2>Login</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Login</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

project/Employees/Employees/Views/Authorization/RegistrationUser.cshtml
@model Employees.Models.RegisterUser

@{
    ViewBag.Title = "RegistrationUser";
    Layout = "~/Views/_layout.cshtml";
}

<h2>Регистрация пользователя</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group .has-error .has-success">
            @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group .has-success">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Зарегистрировать" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>